### ISSUE TITLE
Couldn't find esp_matter_init() function in ESP-MATTER. Is this API correct ?

### ISSUE THREAD

**Issue by aggaddam** [Aethon-Labs/ESP32-Lightbulb-with-Matter-Firmware#1]
I didn't find esp_matter_init() function in ESP-MATTER. Which version of ESP-MATTER are using for this example code ?

**Comment by Dexhub** [comment]
@aggaddam - Looks like that header file has been removed. Let me update the code so that it uses Matter implementation provided by Silicon Labs. The implementation is available on GitHub at https://github.com/project-chip/connectedhomeip/tree/master/examples/platform/esp32.
